- general:
    - ConstantsInInterfaceCheck:
        ignoreIfHasMethods: False
    - CopyPasteCheck:
        tokenCount: 100
    - DoubleBraceInitializationCheck
    - ForToForEachCheck
    - MissingOverrideAnnotationCheck
    - EqualsContractCheck
    - CompareObjectsNotStringsCheck
    - ConstantNamingAndQualifierCheck
    - DontReassignParametersCheck
    - FieldShouldBeLocalCheck
    - WrongLineBreakCheck
- api:
    - IsEmptyReimplementationCheck
    - OldCollectionCheck
    - StringIsEmptyReimplementationCheck
- complexity:
    - DiamondOperatorCheck
    - ExtendsObjectCheck
    - ForLoopVariableCheck
    - RedundantModifierCheck
    - RedundantReturnCheck
    - UnnecessaryLocalBeforeReturnCheck
    - UnusedImportCheck
    - WrapperInstantiationCheck
    - RedundantIfForBooleanCheck
    - SelfAssignmentCheck
    - RepeatedMathOperationCheck
- debug:
    - AssertCheck
    - PrintStackTraceCheck
- exceptions:
    - EmptyCatchCheck
    - RuntimeExceptionCatchCheck
    - CustomExceptionInheritanceCheck
    - ExceptionControlFlowCheck
- comment:
    - JavadocReturnNullCheck
    - CommentLanguageCheck
    - JavadocStubCheck
    - CommentedOutCodeCheck
    - AuthorTagCheck:
        regex: u(\w){4}
    - JavadocParamCheck
- naming:
    - BooleanMethodNameCheck
    - LinguisticNamingCheck
    - VariablesHaveDescriptiveNamesCheck
    - ConstantsHaveDescriptiveNamesCheck
- oop:
    - ConcreteCollectionCheck
    - MethodShouldBeAbstractCheck
    - ListGetterSetterCheck
    - UtilityClassCheck
- structure:
    - DefaultPackageCheck
- unnecessary:
    - EmptyNonCatchBlockCheck
    - UnusedCodeElementCheck
